### ISSUE TITLE
trying to install the 1.19 version fails in Azure

### ISSUE THREAD

**Issue by GaryWenneker** [solvsoftware/Ghost-Azure#19]
Deploying the develop branch (2) works fine.
When trying to deploy the version 1.19 gives me an error:

first run>>

Submitting Deployment
Deployment Started
Creating Web Hosting Plan
Creating Website
Setting up Source Control 
Deployment Failed (View Error) >> The resource operation completed with terminal provisioning state 'Failed'.

second run (after retry):

Submitting Deployment
Deployment Started
Creating Web Hosting Plan
Creating Website
Setting up Source Control 
Deployment Failed (View Error) >> Could not find any source control deployments

Any idea why this happens?

**Comment by RadoslavGatev** [comment]
Hello @GaryWenneker,

Can you provide more detailed logs? For example, you can try opening the resource group where you tried to deploy this and then click on Deployments.

Which GitHub repo do you use?

I will suggest trying with 2.1.0 because 1.19 requires manual execution of npm install and database migration scripts. I tested 2.1.0 yesterday and it's really a one-click deployment.

**Comment by GaryWenneker** [comment]
Sure, the 2.1.0 deploys fine but because I have a theme which only can run on 1.19 I wanted to deploy that one.
