### ISSUE TITLE
Demo Website (https://ghost-azure-demo.azurewebsites.net/) not accessible

### ISSUE THREAD

**Issue by SimonDarksideJ** [solvsoftware/Ghost-Azure#43]
Exactly as it says in the title

**Comment by SimonDarksideJ** [comment]
OK, retracting this issue.  However, there should be a guide pointing out that once you have setup the site, you need to go to a specific Ghost admin URL to configure the site.

By default it shows the Ghost holding page :D

**Comment by RadoslavGatev** [comment]
I was able to get it to work at least yesterday. The problem was that some old *.js files in the Web App used to point to inexisting module. Maybe it was a bug in some of the versions. It's very likely to have some additional issues.

I need to change the deployment so that it deletes any existing files (excluding the content) from the Web App directory.
Leaving this opened until I have more time to check it.

**Comment by RadoslavGatev** [comment]
It's fine now.

**Comment by SimonDarksideJ** [comment]
Great stuff, so is the deployment platform up to date to generate the site?
The version I have deployed atm is soo slow on Azure using this method in V3.

**Comment by RadoslavGatev** [comment]
I think it's stable now. Haven't tested deploying a fresh blog.

I intend to move my blog to v4 in the following days.

**Comment by SimonDarksideJ** [comment]
Great stuff, looking forward to the updated blog post.  Will try recreating my Ghost blog on another subscription before migrating/upgrading the current site I have deployed.

Fantastic work btw
